--AULA DIA 11/05/2026

--2. TRAZER UMA LISTA COM CIDADE, ESTADO E NOME DO PAIS

SELECT city, state_province, country_name
FROM locations loc
RIGHT JOIN countries cnt 
ON loc.country_id = cnt.country_id
LEFT JOIN regions reg 
ON reg.region_id = cnt.region_id
WHERE UPPER(region_name) = UPPER('americas');


--USANDO LIKE E ESCOPOS COM %

SELECT city, state_province, country_name
FROM locations loc
RIGHT JOIN countries cnt ON loc.country_id = cnt.country_id
LEFT JOIN regions reg ON reg.region_id = cnt.region_id
WHERE TRANSLATE(UPPER(region_name), 'ÁÀÃÂÄÉÈÊËÍÌÎÏÓÒÕÔÖÚÙÛÜÇÑ', 'AAAAAEEEEIIIIOOOOOUUUUCN') 
LIKE TRANSLATE(UPPER('américas'), 'ÁÀÃÂÄÉÈÊËÍÌÎÏÓÒÕÔÖÚÙÛÜÇÑ', 'AAAAAEEEEIIIIOOOOOUUUUCN') || '%';

--3. TRAZER UMA LISTAGEM COM O NOME DO FUNCIONARIO, SEU E-MAIL E DEPARTAMENTO
--E O NOME DEPARTAMENTO QUE ELE TRABALHA, ORDENAR ASCENDENTE
--POR NOME DO DEPARTAMENTO

SELECT EMP.FIRST_NAME, EMP.EMAIL,DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP 
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
ORDER BY DEP.DEPARTMENT_NAME ASC;

/*4. TRAZER UMA LISTAGEM COM O NOME DOS DEPARTAMENTOS QUE NÃO FORAM ALOCADOS A NENHUM FUNCIONARIOS*/

SELECT DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP 
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
WHERE DEPARTMENT_NAME IS NULL;

/*5. OS FUNCIONARIOS SEM DEPARTAMENTOS*/

SELECT EMP.FIRST_NAME, EMP.EMAIL,DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP 
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
WHERE DEPARTMENT_NAME IS NULL;

/*6. TRAZER OS NOMES DE CARGOS (JOBS) QUE NUNCA FORAM USADOS EM FUNCIONARIOS */

SELECT FIRST_NAME, JOB_TITLE
FROM EMPLOYEES EMP
RIGHT JOIN JOBS JOB 
ON EMP.JOB_ID = JOB.JOB_ID
WHERE FIRST_NAME IS NULL;

-- AGRUPAMENTO DE VALORES (SOMA, CONTAGEM, MEDIA, MINIMO, MAXIMO) E ARREDONDAMENTO EM AVG (MEDIA)

SELECT 
  SUM(SALARY), 
  COUNT(SALARY), 
  ROUND (AVG(SALARY),2), --ROUND ARRENDONDA PRA CIMA E FLOAR ARREDONDA PRA BAIXO 
  MAX(SALARY), 
  MIN(SALARY)
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--FUNCOES QUE FUNCIONAM COM TEXTO

SELECT
    COUNT(FIRST_NAME),
    MIN(FIRST_NAME),
    MAX(FIRST_NAME)
FROM EMPLOYEES;







































