DROP TABLE ALUNO ;
DROP TABLE CURSO ;
DROP TABLE CURSO_AREA ;
DROP TABLE ALUNO_CURSO;

CREATE TABLE CURSO_AREA(
    COD_AREA NUMBER(2) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_NOME_CURSOAREA UNIQUE (NOME)
);

CREATE TABLE CURSO(
    COD_CURSO NUMBER(4) PRIMARY KEY,
    NOME VARCHAR2(60) NOT NULL,
    COD_AREA NUMBER(2) NOT NULL,
    CONSTRAINT UQ_NOME_CURSO UNIQUE (NOME),
    CONSTRAINT FK_CURSO_CURSO_AREA 
        FOREIGN KEY (COD_AREA) 
        REFERENCES CURSO_AREA (COD_AREA)
);

CREATE TABLE ALUNO(
    RA NUMBER(7) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    CONSTRAINT UQ_CPF_ALUNO UNIQUE (CPF),
    CONSTRAINT CK_GENERO_ALUNO CHECK (GENERO IN ('M','F'))
);

CREATE TABLE ALUNO_CURSO(
RA NUMBER (7),
COD_CURSO NUMBER (4),
DATA_MATRICULA DATE NOT NULL,
DATA_TERMINOU DATE,
CONSTRAINT PK_CURSO_ALUNO PRIMARY KEY (RA, COD_CURSO),
CONSTRAINT PK_ALUNO_ALUNO_CURSO FOREIGN KEY (RA) REFERENCES ALUNO (RA),
CONSTRAINT PK_CURSO_ALUNO_CURSO FOREIGN KEY (COD_CURSO)
                                REFERENCES CURSO (COD_CURSO)
);
