

CREATE TABLE PACIENTE(
    COD_PAC NUMBER(7) PRIMARY KEY,
    NOME_PACIENTE VARCHAR2(120) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR2(14) NULL,
    GENERO CHAR(1) NOT NULL,
    CONSTRAINT UQ_CPF_PACIENTE UNIQUE (CPF),
    CONSTRAINT CK_GENERO_PACIENTE CHECK (GENERO IN ('M', 'F'))
);
 
CREATE TABLE ESPECIALIDADE(
    COD_ESP NUMBER(3) PRIMARY KEY,
    NOME_ESP VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_NOME_ESPECIALIDADE UNIQUE (NOME)
);
 
 
CREATE TABLE MEDICO(
    CRM NUMBER(6) PRIMARY KEY,
    NOME_MEDICO VARCHAR2(120) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    COD_ESP NUMBER(3),
    CONSTRAINT FK_MEDICO_ESPECIALIDADE FOREIGN KEY (COD_ESP)
    REFERENCES ESPECIALIDADE (COD_ESP);
    CONSTRAINT CK_GENERO_MEDICO CHECK (GENERO IN ('M', 'F'))
);
 
 
CREATE TABLE CONSULTA(
    CRM NUMBER(6),
    COD_PAC NUMBER(7),
    DTH_AGENDADO DATE,
    TIPO CHAR(1) NOT NULL,
    SITUACAO CHAR(1) NOT NULL,
    VALOR NUMBER(8,2) NOT NULL,
    DTH_INICIO DATE NULL,
    DTH_FIM DATE,
    DESCRICAO_ATENDIMENTO VARCHAR2(1000) NULL,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (CRM, COD_PAC, DTH_AGENDADO),
    CONSTRAINT FK_MEDICO_CONSULTA FOREIGN KEY (CRM) REFERENCES MEDICO(CRM),
    CONSTRAINT FK_PACIENTE_CONSULTA FOREIGN KEY (COD_PAC) REFERENCES PACIENTE(COD_PAC),
    CONSTRAINT CK_TIPO_CONSULTA CHECK (TIPO IN ('C', 'R')),
    CONSTRAINT CK_SITUACAO_CONSULTA CHECK (SITUACAO IN ('A', 'C', 'R'))
);