DROP TABLE CONSULTA ;
DROP TABLE MEDICO ;
DROP TABLE PACIENTE ;
DROP TABLE ESPECIALIDADE ;


CREATE TABLE ESPECIALIDADE (
    COD_ESPECIALIDADE NUMBER(5) PRIMARY KEY,
    NOME VARCHAR2(60) NOT NULL,
    CONSTRAINT UQ_ESPECIALIDADE_NOME UNIQUE (NOME)
);


CREATE TABLE MEDICO (
    CRM NUMBER(5) PRIMARY KEY,
    NOME VARCHAR2(60) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    COD_ESPECIALIDADE NUMBER(5) NOT NULL,
    
    CONSTRAINT UQ_MEDICO_CPF UNIQUE (CPF),
    
    CONSTRAINT FK_MEDICO_ESPECIALIDADE
        FOREIGN KEY (COD_ESPECIALIDADE)
        REFERENCES ESPECIALIDADE (COD_ESPECIALIDADE)
);


CREATE TABLE PACIENTE (
    COD_PACIENTE NUMBER(11) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    
    CONSTRAINT UQ_PACIENTE_CPF UNIQUE (CPF),
    CONSTRAINT CK_GENERO CHECK (GENERO IN ('M','F'))
);

CREATE TABLE CONSULTA (
    COD_CONSULTA NUMBER(6) PRIMARY KEY,
    DATA_HORA DATE NOT NULL,
    CRM NUMBER(5) NOT NULL,
    COD_PACIENTE NUMBER(11) NOT NULL,
    
    CONSTRAINT FK_CONSULTA_MEDICO
        FOREIGN KEY (CRM)
        REFERENCES MEDICO (CRM),
        
    CONSTRAINT FK_CONSULTA_PACIENTE
        FOREIGN KEY (COD_PACIENTE)
        REFERENCES PACIENTE (COD_PACIENTE)
);